spring:
  application:
    name: Team4_BE

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

jwt:
  expiration-time: 1800000

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    region:
      statics: ap-northeast-2
    s3:
      bucket: nurspace-bucket

kakao:
  api-key: ${KAKAO_API_KEY}
  address-search-url: ${ADDRESS_SEARCH_URL}